Introducción a estructura de datos

In [1]:
import numpy as np
import pandas as pd


In [ ]:
ventas= pd.Series([22,15,70], index=["Enero","Febrero","Marzo"])
ventas

Enero      22
Febrero    15
Marzo      70
dtype: int64

In [ ]:
ventas[0]

<ipython-input-12-eacc5df2ea8a>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ventas[0]


22

In [ ]:
ventas.dtype

dtype('int64')

In [ ]:
ventas.index

Index(['Enero', 'Febrero', 'Marzo'], dtype='object')

In [ ]:
ventas.values

array([22, 15, 70])

In [ ]:
ventas.name="Ventas 2024"
ventas

Enero      22
Febrero    15
Marzo      70
Name: Ventas 2024, dtype: int64

In [ ]:
ventas.index.name="Meses"
ventas

Meses
Enero      22
Febrero    15
Marzo      70
Name: Ventas 2024, dtype: int64

In [ ]:
ventas.shape

(3,)

In [ ]:
medidas=pd.DataFrame({"Humedad":[41,20,30,80],"Salinidad":[22,15,40,80], "Maquinaria":["sí","no", "no", "no"],"Acidez":["alta","media", "baja","alta"], "ph":[3,5,9,12]},index=["La Ureña", "la pedregoza", "Maria Bonita", "Perú"])
medidas

Humedad  Salinidad Maquinaria Acidez  ph
La Ureña           41         22         sí   alta   3
la pedregoza       20         15         no  media   5
Maria Bonita       30         40         no   baja   9
Perú               80         80         no   alta  12

In [ ]:
medidas.index.name="Fincas"
medidas

Humedad  Salinidad Maquinaria Acidez  ph
Fincas                                                
La Ureña           41         22         sí   alta   3
la pedregoza       20         15         no  media   5
Maria Bonita       30         40         no   baja   9
Perú               80         80         no   alta  12

In [ ]:
medidas.columns

Index(['Humedad', 'Salinidad', 'Maquinaria', 'Acidez', 'ph'], dtype='object')

In [ ]:
medidas.axes

[Index(['La Ureña', 'la pedregoza', 'Maria Bonita', 'Perú'], dtype='object', name='Fincas'),
 Index(['Humedad', 'Salinidad', 'Maquinaria', 'Acidez', 'ph'], dtype='object')]

In [ ]:
medidas.values

array([[41, 22, 'sí', 'alta', 3],
       [20, 15, 'no', 'media', 5],
       [30, 40, 'no', 'baja', 9],
       [80, 80, 'no', 'alta', 12]], dtype=object)

In [ ]:
medidas.shape

(4, 5)

In [ ]:
elementos={"numero atómico":[1,6,47,88],"Masa atómico":[1,12,107,226],"Familia":["No metal", "No metal", "Metal","Metal"]}
elementos

{'numero atómico': [1, 6, 47, 88],
 'Masa atómico': [1, 12, 107, 226],
 'Familia': ['No metal', 'No metal', 'Metal', 'Metal']}

In [ ]:
tabla_periodica=pd.DataFrame(elementos, index=["Hidrógeno", "Carbón", "Plata","Radio"],columns=["Familia", "número atomico", "Masa atómica"])
tabla_periodica

Familia número atomico Masa atómica
Hidrógeno  No metal            NaN          NaN
Carbón     No metal            NaN          NaN
Plata         Metal            NaN          NaN
Radio         Metal            NaN          NaN

from matplotlib import pyplot as plt
import seaborn as sns
tabla_periodica.groupby('Familia').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

In [ ]:
unidades=pd.DataFrame(datos)
unidades

NameError: name 'datos' is not defined

In [ ]:
d={"Enero":7,"Febrero":9, "Marzo":3}
type(d)

dict

In [ ]:
s=pd.Series(d)
s

Enero      7
Febrero    9
Marzo      3
dtype: int64

In [ ]:
s.name="valores"
s

Enero      7
Febrero    9
Marzo      3
Name: valores, dtype: int64

In [6]:
datos = np.array([[2, 4, 6, 8], [4, 6, 7, 4], [5, 2, 3, 1]])
datos

array([[2, 4, 6, 8],
       [4, 6, 7, 4],
       [5, 2, 3, 1]])

In [7]:
unidades = pd.DataFrame(datos)
unidades

0  1  2  3
0  2  4  6  8
1  4  6  7  4
2  5  2  3  1

In [9]:
unidades.index = ['La ureña', 'La pedregoza', 'Maria Bonita']
unidades.columns = [2021, 2022, 2023, 2024]
print(unidades)

              2021  2022  2023  2024
La ureña         2     4     6     8
La pedregoza     4     6     7     4
Maria Bonita     5     2     3     1


In [4]:
medida_2020={"Ag":2, "Au":5, "Cu":3, "Pt":2}
medida_2021={"Ag":4, "Au":3, "Cu":6, "Pt":1}
medida_2022={"Ag":8, "Au":2, "Cu":15, "Pt":0}
unidades=pd.DataFrame([medida_2020, medida_2021, medida_2022], index=[2020,2021,2022])
unidades

Ag  Au  Cu  Pt
2020   2   5   3   2
2021   4   3   6   1
2022   8   2  15   0

In [14]:
titanic = pd.read_csv("/content/titanic-train.csv")
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [15]:

titanic.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [16]:

titanic.tail()


PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [17]:
titanic.sample(5)

PassengerId  Survived  Pclass                                   Name  \
312          313         0       2  Lahtinen, Mrs. William (Anna Sylfven)   
753          754         0       3                     Jonkoff, Mr. Lalio   
667          668         0       3             Rommetvedt, Mr. Knud Paust   
235          236         0       3           Harknett, Miss. Alice Phoebe   
26            27         0       3                Emir, Mr. Farred Chehab   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
312  female  26.0      1      1      250651  26.0000   NaN        S  
753    male  23.0      0      0      349204   7.8958   NaN        S  
667    male   NaN      0      0      312993   7.7750   NaN        S  
235  female   NaN      0      0  W./C. 6609   7.5500   NaN        S  
26     male   NaN      0      0        2631   7.2250   NaN        C

In [18]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [20]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [24]:
import pandas as pd
import numpy as np # Import NumPy for np.nan

s = pd.Series([3, 1, 2, 1, 1, 4, 1, 2, np.nan, np.nan]) # changed to np.nan here
s.value_counts()

1.0    4
2.0    2
3.0    1
4.0    1
Name: count, dtype: int64

In [21]:
titanic.value_counts()

PassengerId  Survived  Pclass  Name                                                  Sex     Age   SibSp  Parch  Ticket    Fare      Cabin  Embarked
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)   female  38.0  1      0      PC 17599  71.2833   C85    C           1
572          1         1       Appleton, Mrs. Edward Dale (Charlotte Lamson)         female  53.0  2      0      11769     51.4792   C101   S           1
578          1         1       Silvey, Mrs. William Baird (Alice Munger)             female  39.0  1      0      13507     55.9000   E44    S           1
582          1         1       Thayer, Mrs. John Borland (Marian Longstreth Morris)  female  39.0  1      1      17421     110.8833  C68    C           1
584          0         1       Ross, Mr. John Hugo                                   male    36.0  0      0      13049     40.1250   A10    C           1
                                                                                                                                                       ..
328          1         2       Ball, Mrs. (Ada E Hall)                               female  36.0  0      0      28551     13.0000   D      S           1
330          1         1       Hippach, Miss. Jean Gertrude                          female  16.0  0      1      111361    57.9792   B18    C           1
332          0         1       Partner, Mr. Austen                                   male    45.5  0      0      113043    28.5000   C124   S           1
333          0         1       Graham, Mr. George Edward                             male    38.0  0      1      PC 17582  153.4625  C91    S           1
890          1         1       Behr, Mr. Karl Howell                                 male    26.0  0      0      111369    30.0000   C148   C           1
Name: count, Length: 183, dtype: int64